implemented search cli command to return found packages from configur…
kndpio/cli pull request #107
Opened 2024-04-18 12:06 UTC by ca7alindev

…ed ghcr.io registry in table format

2024-04-18 12:16 UTC, evghen1 commented on cmd/kndp/search/search.go
> +}
@ca7alindev Please move it to github search package and make it switchable based on found registry url. Next will be GCP, i think we will have messy code when will put everything into single CMD package.
Keep in mind we will have TUI version where also will be search, which call this search system internally,

2024-04-18 13:06 UTC, ca7alindev commented on cmd/kndp/search/search.go
> +}
@evghen1 fixed

2024-04-18 15:29 UTC, evghen1 requested changes

2024-04-18 15:29 UTC, evghen1 commented on internal/search/search.go
@ca7alindev Shall be separate package for github

2024-04-18 15:29 UTC, evghen1 commented on internal/search/search.go
> +func GitHubreg(ctx context.Context, query string, versions bool, r *registry.Registry, registryUrl string, org string, logger *log.Logger) error {
@ca7alindev Please rename it, because i don't understand what that name means.

2024-04-18 15:29 UTC, evghen1 commented on internal/search/search.go
> +		pterm.DefaultTable.WithHasHeader().WithData(tableRegs).Render()
@ca7alindev Don't use direct output from internal packages, return data and in cmd package display it as table.
Remember i talked about TUI, there we use different UI element for display search results.

2024-04-18 15:29 UTC, evghen1 commented on cmd/kndp/search/search.go
> +
@ca7alindev move it to registry package

2024-04-19 13:38 UTC, ca7alindev commented on cmd/kndp/registry/search.go
> +			}
@evghen1 you mean to implement logic for display table in a separate function?

2024-04-19 13:57 UTC, evghen1 commented on cmd/kndp/registry/search.go
> +			}
@ca7alindev No, i meant move all lines from 39 to 62 to github package.

2024-04-19 15:12 UTC, evghen1 requested changes

2024-04-19 15:12 UTC, evghen1 commented on cmd/kndp/registry/search.go
> +	}
@ca7alindev move this to internal search package.

2024-04-19 15:12 UTC, evghen1 commented on cmd/kndp/registry/search.go
> +			_, _, err := github.GetGithubPackages(ctx, c.Query, c.Versions, r, registryUrl, org, logger)
@ca7alindev Do not put default to be github, because if is not github, can't be github. Just skip this registry if is not supported.

2024-04-22 12:15 UTC, evghen1 requested changes

2024-04-22 12:15 UTC, evghen1 commented on internal/github/github.go
> +func GetGithubPackages(ctx context.Context, query string, version bool, r *registry.Registry, registryUrl string, org string, logger *log.Logger) ([]*github.Package, map[string][]*github.PackageVersi
@ca7alindev Le't unify it, and rename it to GetPackages, later in eg. GCP package will be same method.

2024-04-22 12:15 UTC, evghen1 commented on internal/github/github.go
> +		pterm.DefaultTable.WithHasHeader().WithData(tableRegs).Render()
@ca7alindev Move out table usage to cmd/ level, because it's related to view.

2024-04-22 12:15 UTC, evghen1 commented on internal/search/search.go
> +func SearchCmd(ctx context.Context, client *kubernetes.Clientset, config *rest.Config, query string, versions bool, logger *log.Logger) error {
@ca7alindev Please rename it to SearchPackages

2024-04-22 17:08 UTC, evghen1 approved these changes

2024-04-22 17:09 UTC, merged