use name of env created to get config where engine will be installed
kndpio/cli pull request #123
Opened 2024-05-30 10:48 UTC by ca7alindev

2024-05-30 12:34 UTC, evghen1 commented
@ca7alindev Solution not working, return error:
```
$ go run cmd/kndp/main.go env create local
INFO Creating environment with Kubernetes engine 'kind'
FATA context "kind-local" does not exist
exit status 1
```

2024-05-30 12:34 UTC, evghen1 requested changes
Please test solution.

2024-05-30 14:04 UTC, evghen1 requested changes

2024-05-30 14:04 UTC, evghen1 commented on internal/environment/kind.go
> +			logger.Fatalf("%s: host port %d already in use", line, hostPort)
@ca7alindev Ahahaha... Do you think just single type of error will happens?

2024-05-30 14:13 UTC, ca7alindev commented on internal/environment/kind.go
> +			logger.Fatalf("%s: host port %d already in use", line, hostPort)
@evghen1 , no but at least we need to print errors if exists

2024-05-30 14:19 UTC, evghen1 commented on internal/environment/kind.go
> +			logger.Fatalf("%s: host port %d already in use", line, hostPort)
@ca7alindev You print  all errors as already in use port, not? Exists other errors.

2024-05-30 14:22 UTC, ca7alindev commented on internal/environment/kind.go
> +			logger.Fatalf("%s: host port %d already in use", line, hostPort)
@evghen1 then i will let just the error printed without other custom description?

2024-06-04 14:06 UTC, evghen1 approved these changes

2024-06-04 14:06 UTC, merged