remove incrementing patch version, use version given from input
kndpio/cli pull request #141
Opened 2024-06-18 11:24 UTC by ca7alindev

2024-06-18 11:33 UTC, evghen1 requested changes

2024-06-18 11:33 UTC, evghen1 commented on internal/configuration/load.go
> +	c.Name = strings.Join([]string{cRef.Context().Name(), version.String()}, tagDelim)
Is not what I meant, it shall not use manual entered version, if was to be so simple I was not reported issue for that. You have still to make increment, but in case if minor version is changed make increment already based on new version.

2024-06-18 12:17 UTC, ca7alindev commented on internal/configuration/load.go
> +	c.Name = strings.Join([]string{cRef.Context().Name(), version.String()}, tagDelim)
@evghen1 fixed

2024-06-18 12:25 UTC, evghen1 requested changes
Please make it not just minor but also major part change.

2024-06-24 14:30 UTC, evghen1 requested changes

2024-06-24 14:30 UTC, evghen1 commented on internal/configuration/load.go
> +			cRefVersion, _ = semver.NewVersion(cRef.Identifier())
@ca7alindev Looks to complicated, just add condition by minor version additionally to by name, and if minor version do match, we have to deploy new version. 
For example if deployed 3.9.12, but we try to deploy 4.1 or 4.1.12,
 you have to reduce both version to minor, 3.9 and 4.1, compare them and if they match use deployed version if not use requested 4.1

2024-06-24 15:57 UTC, evghen1 requested changes

2024-06-25 10:10 UTC, ca7alindev commented
@evghen1 unfortunately semver package does nor provide a method for reducing version, and also when try to create a new version it requires mandatory parameters for major, minor and patch all of types uint64, so patch anyway should be a number from 0..., comparing major and minor separately is not a good solution?

2024-06-25 10:34 UTC, ca7alindev commented
@evghen1 please review

2024-06-25 15:28 UTC, evghen1 approved these changes

2024-06-25 15:28 UTC, merged