added kyverno policy for patching pods matched by local registry image
kndpio/cli pull request #181
Opened 2024-07-08 14:45 UTC by ca7alindev

2024-07-09 11:24 UTC, evghen1 requested changes

2024-07-09 11:24 UTC, evghen1 commented on internal/registry/local.go
> +	r.Name = svcName
@ca7alindev Why you change here name of registry?

2024-07-09 11:34 UTC, ca7alindev commented on internal/registry/local.go
> +	r.Name = svcName
@evghen1 because svcName it's used at kyverno registry policy creation for policy naming

2024-07-09 13:46 UTC, evghen1 requested changes

2024-07-09 13:46 UTC, evghen1 commented on internal/policy/kyverno.go
> +													"(image)": "*registry.kndp-system.svc.cluster.local*",
@ca7alindev Please use variables and constants from packages, but do not hardcoded full URL

2024-07-09 13:46 UTC, evghen1 commented on internal/registry/registry.go
> +		err = policy.AddLocalRegistryPolicy(ctx, config, &policy.RegistryPolicy{Name: r.Name})
@ca7alindev You could use r.Domain() instead of r.Name and do no change it inside of r.CreateLocal()

2024-07-09 18:18 UTC, evghen1 requested changes

2024-07-09 18:18 UTC, evghen1 commented on internal/policy/kyverno.go
> +	registryURL         = "registry.kndp-system.svc.cluster.local"
@ca7alindev r.Domain() return this url, and you already passed this url as name of policy, use it, don't make additional constant.

2024-07-10 07:01 UTC, evghen1 approved these changes

2024-07-10 07:01 UTC, merged