create environment configuration
kndpio/cli pull request #190
Opened 2024-07-18 15:10 UTC by ca7alindev

2024-07-18 16:49 UTC, evghen1 requested changes

2024-07-18 16:49 UTC, evghen1 commented on configuration/composition.yaml
> +    apiVersion: web7.md/v1alpha1
@ca7alindev Please use kndp.io group

2024-07-18 16:49 UTC, evghen1 commented on configuration/composition.yaml
> +        toFieldPath: "metadata.name"
@ca7alindev Please use Helm Provider config from XRD

2024-07-18 16:49 UTC, evghen1 commented on configuration/composition.yaml
> +
@ca7alindev Remove this, use provider from XRD params.

2024-07-18 16:49 UTC, evghen1 commented on configuration/composition.yaml
> +        toFieldPath: metadata.name
@ca7alindev Local registry is not part of this compositions, is linked to load system of kndp not to environment,

2024-07-18 16:49 UTC, evghen1 commented on configuration/composition.yaml
> +        toFieldPath: spec.forProvider.manifest.stringData.email
@ca7alindev Not sure is so simple, we have to create dockerconfigjson structure, not simple secret.

2024-07-18 16:49 UTC, evghen1 commented on configuration/composition.yaml
> +        toFieldPath: spec.forProvider.manifest.spec.rules[0].generate.namespace
@ca7alindev Let's discuss how to implement this policies, because they shall be linked to multiple registries not just to [0]

2024-07-18 16:49 UTC, evghen1 commented on configuration/composition.yaml
> +        toFieldPath: spec.forProvider.manifest.metadata.name
@ca7alindev Remove local registryservice from this composition

2024-07-18 16:49 UTC, evghen1 commented on configuration/crossplane.yaml
> +      version: ">=v0.16.0"
@ca7alindev Remove this dependency after Helm ProviderConfig in composition

2024-07-18 16:49 UTC, evghen1 commented on configuration/environment.yaml
@ca7alindev Move this object to Helm release values of crossplane

2024-07-18 16:49 UTC, evghen1 commented on configuration/xrd.yaml
> +                environment:
@ca7alindev Remove this environment key, why you need it, in this XRD nothing else except environment parameters, do not required to indicate it twice.

2024-07-29 10:02 UTC, evghen1 approved these changes

2024-07-29 10:03 UTC, evghen1 commented
@ca7alindev Please resolve confilicts

2024-07-29 10:14 UTC, ca7alindev commented
> @ca7alindev Please resolve confilicts

@evghen1 this PR should be closed in favor of #192

2024-07-30 08:23 UTC, closed without merging