Implemented 'e' flag for 'kndp env create' to select Kubernetes engin…
kndpio/cli pull request #72
Opened 2024-03-01 15:35 UTC by ca7alindev

…e for environment creation.

2024-03-01 16:31 UTC, web7evgheni requested changes

2024-03-01 16:31 UTC, web7evgheni commented on cmd/kndp/environment/create.go
@ca7alindev Please move all kind and k3s functions to separate internal files, later we will use them as Go plugins.

2024-03-05 07:49 UTC, evghen7 requested changes

2024-03-05 07:49 UTC, evghen7 commented on cmd/kndp/environment/create.go
> +		err := environment.K3sCluster(c.Context, logger)
@ca7alindev Please replace it with swtich

2024-03-05 07:49 UTC, evghen7 commented on cmd/kndp/environment/create.go
> +		logger.Fatal("Kubernetes engine not supported")
@ca7alindev Please add parameter value to be clear which engine was provided.

2024-03-05 07:49 UTC, evghen7 commented on cmd/kndp/environment/create.go
> +			return nil
@ca7alindev this return not required because, no other code blocks.

2024-03-05 07:49 UTC, evghen7 commented on internal/environment/k3s.go
> +	os.Setenv("KUBECONFIG", "/etc/rancher/k3s/k3s.yaml")
@ca7alindev Best to take it from current environment, and just if not provided, use default.

2024-03-05 07:49 UTC, evghen7 commented on internal/environment/k3s.go
> +	cmd := exec.Command("sh", "-c", "curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='--write-kubeconfig-mode 644' sh -")
@ca7alindev Please do not install k3s just create cluster.

2024-03-05 07:49 UTC, evghen7 commented on internal/environment/kind.go
> +		}
@ca7alindev move this to cmd

2024-03-05 07:49 UTC, evghen7 commented on internal/environment/kind.go
> +func KindCluster(context string, logger *log.Logger, name string, hostPort int, yamlTemplate string) {
@ca7alindev Rename it KindEnvironment because we not creating just cluster.

2024-03-05 07:49 UTC, evghen7 commented on internal/environment/k3s.go
> +func K3sCluster(context string, logger *log.Logger) error {
@ca7alindev Rename it to K3sEnvironment because we not creating just cluster.

2024-03-05 07:49 UTC, evghen7 commented on internal/environment/environment.go
> +func installHelmResources(configClient *rest.Config, logger *log.Logger) error {
@ca7alindev Rename it to installEngine because could be not used helm in the future.

2024-03-05 20:46 UTC, evghen7 commented
@ca7alindev Any news?

2024-03-06 08:17 UTC, ca7alindev commented on internal/environment/k3s.go
> +	cmd := exec.Command("sh", "-c", "curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='--write-kubeconfig-mode 644' sh -")
@evghen7, but the installation process itself is the cluster creation process, when install k3s anyway it creates a single node cluster, k3s does not provide a cli command just like kind to create multiple clusters with custom proprieties such as cluster name etc. , for that we will need to use same approach like we did with kind, another tool which will bootstrap k3s clusters in docker like k3d.

2024-03-06 15:55 UTC, evghen7 requested changes

2024-03-06 15:55 UTC, evghen7 commented on internal/environment/k3s.go
> +	cmd := exec.Command("sh", "-c", "curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='--write-kubeconfig-mode 644' sh -")
@ca7alindev Sorry, but you not right, almost everything has alternative ways to install, what you see from get started is just simplest one :)
https://docs.k3s.io/installation/configuration#configuration-with-binary

2024-03-06 15:58 UTC, evghen7 commented
`k3s server \
  --write-kubeconfig-mode "0644"    \
  --tls-san "foo.local"             \
  --node-label "foo=bar"            \
  --node-label "something=amazing"  \
  --cluster-init`

2024-03-09 11:26 UTC, evghen7 approved these changes

2024-03-09 11:26 UTC, merged